npmRegistryServer: "http://localhost:4873"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.js
    spec: "@yarnpkg/plugin-version"

unsafeHttpWhitelist: localhost

yarnPath: .yarn/releases/yarn-sources.js
